In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("train.csv")

In [3]:
type(dataset)

pandas.core.frame.DataFrame

In [4]:
dataset.head()

ID  Customer_ID  Month           Name  Age        SSN Occupation  \
0  5634         3392      1  Aaron Maashoh   23  821000265  Scientist   
1  5635         3392      2  Aaron Maashoh   23  821000265  Scientist   
2  5636         3392      3  Aaron Maashoh   23  821000265  Scientist   
3  5637         3392      4  Aaron Maashoh   23  821000265  Scientist   
4  5638         3392      5  Aaron Maashoh   23  821000265  Scientist   

   Annual_Income  Monthly_Inhand_Salary  Num_Bank_Accounts  ...  Credit_Mix  \
0       19114.12            1824.843333                  3  ...        Good   
1       19114.12            1824.843333                  3  ...        Good   
2       19114.12            1824.843333                  3  ...        Good   
3       19114.12            1824.843333                  3  ...        Good   
4       19114.12            1824.843333                  3  ...        Good   

   Outstanding_Debt  Credit_Utilization_Ratio Credit_History_Age  \
0            809.98                 26.822620                265   
1            809.98                 31.944960                266   
2            809.98                 28.609352                267   
3            809.98                 31.377862                268   
4            809.98                 24.797347                269   

   Payment_of_Min_Amount  Total_EMI_per_month  Amount_invested_monthly  \
0                     No            49.574949                 21.46538   
1                     No            49.574949                 21.46538   
2                     No            49.574949                 21.46538   
3                     No            49.574949                 21.46538   
4                     No            49.574949                 21.46538   

                  Payment_Behaviour Monthly_Balance  Credit_Score  
0   High_spent_Small_value_payments      312.494089          Good  
1    Low_spent_Large_value_payments      284.629163          Good  
2   Low_spent_Medium_value_payments      331.209863          Good  
3    Low_spent_Small_value_payments      223.451310          Good  
4  High_spent_Medium_value_payments      341.489231          Good  

[5 rows x 28 columns]

In [5]:
dataset.tail()

ID  Customer_ID  Month   Name  Age       SSN Occupation  \
99995  155625        37932      4  Nicks   25  78735990   Mechanic   
99996  155626        37932      5  Nicks   25  78735990   Mechanic   
99997  155627        37932      6  Nicks   25  78735990   Mechanic   
99998  155628        37932      7  Nicks   25  78735990   Mechanic   
99999  155629        37932      8  Nicks   25  78735990   Mechanic   

       Annual_Income  Monthly_Inhand_Salary  Num_Bank_Accounts  ...  \
99995       39628.99            3359.415833                  4  ...   
99996       39628.99            3359.415833                  4  ...   
99997       39628.99            3359.415833                  4  ...   
99998       39628.99            3359.415833                  4  ...   
99999       39628.99            3359.415833                  4  ...   

       Credit_Mix  Outstanding_Debt  Credit_Utilization_Ratio  \
99995        Good            502.38                 34.663572   
99996        Good            502.38                 40.565631   
99997        Good            502.38                 41.255522   
99998        Good            502.38                 33.638208   
99999        Good            502.38                 34.192463   

      Credit_History_Age  Payment_of_Min_Amount  Total_EMI_per_month  \
99995                378                     No            35.104023   
99996                379                     No            35.104023   
99997                380                     No            35.104023   
99998                381                     No            35.104023   
99999                382                     No            35.104023   

       Amount_invested_monthly                 Payment_Behaviour  \
99995                24.028477   High_spent_Large_value_payments   
99996                24.028477  High_spent_Medium_value_payments   
99997                24.028477   High_spent_Large_value_payments   
99998                24.028477    Low_spent_Large_value_payments   
99999                24.028477    Low_spent_Small_value_payments   

      Monthly_Balance  Credit_Score  
99995      479.866228          Poor  
99996      496.651610          Poor  
99997      516.809083          Poor  
99998      319.164979      Standard  
99999      393.673696          Poor  

[5 rows x 28 columns]

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype  
---  ------                    --------------   -----  
 0   ID                        100000 non-null  int64  
 1   Customer_ID               100000 non-null  int64  
 2   Month                     100000 non-null  int64  
 3   Name                      99990 non-null   object 
 4   Age                       100000 non-null  int64  
 5   SSN                       100000 non-null  int64  
 6   Occupation                99995 non-null   object 
 7   Annual_Income             100000 non-null  float64
 8   Monthly_Inhand_Salary     100000 non-null  float64
 9   Num_Bank_Accounts         100000 non-null  int64  
 10  Num_Credit_Card           100000 non-null  int64  
 11  Interest_Rate             100000 non-null  int64  
 12  Num_of_Loan               100000 non-null  int64  
 13  Type_of_Loan              100000 non-null  ob

In [7]:
dataset.columns

Index(['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation',
       'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts',
       'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan',
       'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit',
       'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt',
       'Credit_Utilization_Ratio', 'Credit_History_Age',
       'Payment_of_Min_Amount', 'Total_EMI_per_month',
       'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance',
       'Credit_Score'],
      dtype='object')

In [8]:
dataset.shape

(100000, 28)

In [9]:
dataset.describe()

ID    Customer_ID          Month            Age  \
count  100000.000000  100000.000000  100000.000000  100000.000000   
mean    80631.500000   25982.666640       4.500000      33.316340   
std     43301.486619   14340.543051       2.291299      10.764812   
min      5634.000000    1006.000000       1.000000      14.000000   
25%     43132.750000   13664.500000       2.750000      24.000000   
50%     80631.500000   25777.000000       4.500000      33.000000   
75%    118130.250000   38385.000000       6.250000      42.000000   
max    155629.000000   50999.000000       8.000000      56.000000   

                SSN  Annual_Income  Monthly_Inhand_Salary  Num_Bank_Accounts  \
count  1.000000e+05  100000.000000          100000.000000      100000.000000   
mean   5.004617e+08   50505.123449            4197.270835           5.368820   
std    2.908267e+08   38299.422093            3186.432497           2.593314   
min    8.134900e+04    7005.930000             303.645417           0.000000   
25%    2.451686e+08   19342.972500            1626.594167           3.000000   
50%    5.006886e+08   36999.705000            3095.905000           5.000000   
75%    7.560027e+08   71683.470000            5957.715000           7.000000   
max    9.999934e+08  179987.280000           15204.633330          11.000000   

       Num_Credit_Card  Interest_Rate  ...  Delay_from_due_date  \
count    100000.000000   100000.00000  ...         100000.00000   
mean          5.533570       14.53208  ...             21.08141   
std           2.067098        8.74133  ...             14.80456   
min           0.000000        1.00000  ...              0.00000   
25%           4.000000        7.00000  ...             10.00000   
50%           5.000000       13.00000  ...             18.00000   
75%           7.000000       20.00000  ...             28.00000   
max          11.000000       34.00000  ...             62.00000   

       Num_of_Delayed_Payment  Changed_Credit_Limit  Num_Credit_Inquiries  \
count           100000.000000         100000.000000         100000.000000   
mean                13.313120             10.470323              5.798250   
std                  6.237166              6.609481              3.867826   
min                  0.000000              0.500000              0.000000   
25%                  9.000000              5.380000              3.000000   
50%                 14.000000              9.400000              5.000000   
75%                 18.000000             14.850000              8.000000   
max                 25.000000             29.980000             17.000000   

       Outstanding_Debt  Credit_Utilization_Ratio  Credit_History_Age  \
count     100000.000000             100000.000000       100000.000000   
mean        1426.220376                 32.285173          221.220460   
std         1155.129026                  5.116875           99.680716   
min            0.230000                 20.000000            1.000000   
25%          566.072500                 28.052567          144.000000   
50%         1166.155000                 32.305784          219.000000   
75%         1945.962500                 36.496663          302.000000   
max         4998.070000                 50.000000          404.000000   

       Total_EMI_per_month  Amount_invested_monthly  Monthly_Balance  
count        100000.000000            100000.000000    100000.000000  
mean            107.699208                55.101315       392.697586  
std             132.267056                39.006932       201.652719  
min               0.000000                 0.000000         0.007760  
25%              29.268886                27.959111       267.615983  
50%              66.462304                45.156550       333.865366  
75%             147.392573                71.295797       463.215683  
max            1779.103254               434.191089      1183.930696  

[8 rows x 21 columns]

In [10]:
dataset

ID  Customer_ID  Month           Name  Age        SSN Occupation  \
0        5634         3392      1  Aaron Maashoh   23  821000265  Scientist   
1        5635         3392      2  Aaron Maashoh   23  821000265  Scientist   
2        5636         3392      3  Aaron Maashoh   23  821000265  Scientist   
3        5637         3392      4  Aaron Maashoh   23  821000265  Scientist   
4        5638         3392      5  Aaron Maashoh   23  821000265  Scientist   
...       ...          ...    ...            ...  ...        ...        ...   
99995  155625        37932      4          Nicks   25   78735990   Mechanic   
99996  155626        37932      5          Nicks   25   78735990   Mechanic   
99997  155627        37932      6          Nicks   25   78735990   Mechanic   
99998  155628        37932      7          Nicks   25   78735990   Mechanic   
99999  155629        37932      8          Nicks   25   78735990   Mechanic   

       Annual_Income  Monthly_Inhand_Salary  Num_Bank_Accounts  ...  \
0           19114.12            1824.843333                  3  ...   
1           19114.12            1824.843333                  3  ...   
2           19114.12            1824.843333                  3  ...   
3           19114.12            1824.843333                  3  ...   
4           19114.12            1824.843333                  3  ...   
...              ...                    ...                ...  ...   
99995       39628.99            3359.415833                  4  ...   
99996       39628.99            3359.415833                  4  ...   
99997       39628.99            3359.415833                  4  ...   
99998       39628.99            3359.415833                  4  ...   
99999       39628.99            3359.415833                  4  ...   

       Credit_Mix  Outstanding_Debt  Credit_Utilization_Ratio  \
0            Good            809.98                 26.822620   
1            Good            809.98                 31.944960   
2            Good            809.98                 28.609352   
3            Good            809.98                 31.377862   
4            Good            809.98                 24.797347   
...           ...               ...                       ...   
99995        Good            502.38                 34.663572   
99996        Good            502.38                 40.565631   
99997        Good            502.38                 41.255522   
99998        Good            502.38                 33.638208   
99999        Good            502.38                 34.192463   

      Credit_History_Age  Payment_of_Min_Amount  Total_EMI_per_month  \
0                    265                     No            49.574949   
1                    266                     No            49.574949   
2                    267                     No            49.574949   
3                    268                     No            49.574949   
4                    269                     No            49.574949   
...                  ...                    ...                  ...   
99995                378                     No            35.104023   
99996                379                     No            35.104023   
99997                380                     No            35.104023   
99998                381                     No            35.104023   
99999                382                     No            35.104023   

       Amount_invested_monthly                 Payment_Behaviour  \
0                    21.465380   High_spent_Small_value_payments   
1                    21.465380    Low_spent_Large_value_payments   
2                    21.465380   Low_spent_Medium_value_payments   
3                    21.465380    Low_spent_Small_value_payments   
4                    21.465380  High_spent_Medium_value_payments   
...                        ...                               ...   
99995                24.028477   High_spent_Large_value_payments   
99996              

In [11]:
X = dataset.iloc[ : , 0:-1].values
y = dataset.iloc[ : , -1].values

In [12]:
# from sklearn.preprocessing import LabelEncoder
# le_test = LabelEncoder()
# print(X[: , 0])
# test = le_test.fit_transform(X[: , 0])
# print(test)

In [13]:
from sklearn.impute import SimpleImputer

In [14]:
imputer = SimpleImputer(strategy='most_frequent', missing_values=np.nan)

In [15]:
dataset[["Name", "Credit_Score"]] = imputer.fit_transform(dataset[["Name", "Credit_Score"]])

In [16]:
mode=dataset.filter(["Name","Credit_Score"])

In [17]:
cols = ["Name","Credit_Score"]
dataset[cols]=dataset[cols].fillna(mode.iloc[0:27])

In [18]:
print(X)

[[5634 3392 1 ... 21.46538026 'High_spent_Small_value_payments'
  312.4940887]
 [5635 3392 2 ... 21.46538026 'Low_spent_Large_value_payments'
  284.6291625]
 [5636 3392 3 ... 21.46538026 'Low_spent_Medium_value_payments'
  331.2098629]
 ...
 [155627 37932 6 ... 24.02847745 'High_spent_Large_value_payments'
  516.8090833]
 [155628 37932 7 ... 24.02847745 'Low_spent_Large_value_payments'
  319.1649785]
 [155629 37932 8 ... 24.02847745 'Low_spent_Small_value_payments'
  393.6736956]]


In [19]:
print(y)

['Good' 'Good' 'Good' ... 'Poor' 'Standard' 'Poor']


In [20]:
#Encoding the Dependent Variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [21]:
dataset["Name"]=le.fit_transform(dataset["Name"])
dataset["Occupation"]=le.fit_transform(dataset["Occupation"])
dataset["Annual_Income"]=le.fit_transform(dataset["Annual_Income"])
dataset["Monthly_Inhand_Salary"]=le.fit_transform(dataset["Monthly_Inhand_Salary"])
dataset["Type_of_Loan"]=le.fit_transform(dataset["Type_of_Loan"])
dataset["Changed_Credit_Limit"]=le.fit_transform(dataset["Changed_Credit_Limit"])
dataset["Credit_Mix"]=le.fit_transform(dataset["Credit_Mix"])
dataset["Outstanding_Debt"]=le.fit_transform(dataset["Outstanding_Debt"])
dataset["Credit_Utilization_Ratio"]=le.fit_transform(dataset["Credit_Utilization_Ratio"])
dataset["Payment_of_Min_Amount"]=le.fit_transform(dataset["Payment_of_Min_Amount"])
dataset["Payment_Behaviour"]=le.fit_transform(dataset["Payment_Behaviour"])
dataset["Monthly_Balance"]=le.fit_transform(dataset["Monthly_Balance"])
dataset["Credit_Score"]=le.fit_transform(dataset["Credit_Score"])
dataset["Total_EMI_per_month"]=le.fit_transform(dataset["Total_EMI_per_month"])
dataset["Amount_invested_monthly"]=le.fit_transform(dataset["Amount_invested_monthly"])

In [22]:
dataset.isnull().sum()

ID                          0
Customer_ID                 0
Month                       0
Name                        0
Age                         0
SSN                         0
Occupation                  0
Annual_Income               0
Monthly_Inhand_Salary       0
Num_Bank_Accounts           0
Num_Credit_Card             0
Interest_Rate               0
Num_of_Loan                 0
Type_of_Loan                0
Delay_from_due_date         0
Num_of_Delayed_Payment      0
Changed_Credit_Limit        0
Num_Credit_Inquiries        0
Credit_Mix                  0
Outstanding_Debt            0
Credit_Utilization_Ratio    0
Credit_History_Age          0
Payment_of_Min_Amount       0
Total_EMI_per_month         0
Amount_invested_monthly     0
Payment_Behaviour           0
Monthly_Balance             0
Credit_Score                0
dtype: int64

In [23]:
print(y)

[0 0 0 ... 1 2 1]


In [24]:
X = dataset.iloc[ : , 0:-1].values
y = dataset.iloc[ : , -1].values

In [25]:
from imblearn.over_sampling import RandomOverSampler
ros=RandomOverSampler(random_state=0)
X_res , y_res=ros.fit_resample(X,y)

In [26]:
print(X)

[[  5634   3392      1 ...   1614      2  41732]
 [  5635   3392      2 ...   1614      3  30890]
 [  5636   3392      3 ...   1614      4  47976]
 ...
 [155627  37932      6 ...   2090      0  78877]
 [155628  37932      7 ...   2090      3  43999]
 [155629  37932      8 ...   2090      5  63175]]


In [27]:
dataset

ID  Customer_ID  Month  Name  Age        SSN  Occupation  \
0        5634         3392      1    11   23  821000265          12   
1        5635         3392      2    11   23  821000265          12   
2        5636         3392      3    11   23  821000265          12   
3        5637         3392      4    11   23  821000265          12   
4        5638         3392      5    11   23  821000265          12   
...       ...          ...    ...   ...  ...        ...         ...   
99995  155625        37932      4  6508   25   78735990           9   
99996  155626        37932      5  6508   25   78735990           9   
99997  155627        37932      6  6508   25   78735990           9   
99998  155628        37932      7  6508   25   78735990           9   
99999  155629        37932      8  6508   25   78735990           9   

       Annual_Income  Monthly_Inhand_Salary  Num_Bank_Accounts  ...  \
0               3021                   3971                  3  ...   
1               3021                   3971                  3  ...   
2               3021                   3971                  3  ...   
3               3021                   3971                  3  ...   
4               3021                   3971                  3  ...   
...              ...                    ...                ...  ...   
99995           6600                   7085                  4  ...   
99996           6600                   7085                  4  ...   
99997           6600                   7085                  4  ...   
99998           6600                   7085                  4  ...   
99999           6600                   7085                  4  ...   

       Credit_Mix  Outstanding_Debt  Credit_Utilization_Ratio  \
0               1              4265                     17956   
1               1              4265                     47807   
2               1              4265                     28196   
3               1              4265                     44460   
4               1              4265                      7373   
...           ...               ...                       ...   
99995           1              2665                     63983   
99996           1              2665                     96066   
99997           1              2665                     97680   
99998           1              2665                     57961   
99999           1              2665                     61258   

       Credit_History_Age  Payment_of_Min_Amount  Total_EMI_per_month  \
0                     265                      1                 3662   
1                     266                      1                 3662   
2                     267                      1                 3662   
3                     268                      1                 3662   
4                     269                      1                 3662   
...                   ...                    ...                  ...   
99995                 378                      1                 2347   
99996                 379                      1                 2347   
99997                 380                      1                 2347   
99998                 381                      1                 2347   
99999                 382                      1                 2347   

       Amount_invested_monthly  Payment_Behaviour  Monthly_Balance  \
0                         1614                  2            41732   
1                         1614                  3            30890   
2                         1614                  4            47976   
3                         1614                  5            11013   
4                         1614                  1            51160   
...                        ...                ...              ...   
99995                     2090                  0            75545   
99996                     2090                  1            77227   
99997            

In [28]:
X

array([[  5634,   3392,      1, ...,   1614,      2,  41732],
       [  5635,   3392,      2, ...,   1614,      3,  30890],
       [  5636,   3392,      3, ...,   1614,      4,  47976],
       ...,
       [155627,  37932,      6, ...,   2090,      0,  78877],
       [155628,  37932,      7, ...,   2090,      3,  43999],
       [155629,  37932,      8, ...,   2090,      5,  63175]], dtype=int64)

In [29]:
#Splitting The Dataset Into Training Set and Testing Set
from sklearn.model_selection import train_test_split

In [30]:
X_train , X_test , y_train, y_test = train_test_split( X_res, y_res, test_size = 0.33, random_state = 42)

In [31]:
X_train

array([[ 73642,  26779,      5, ...,   2292,      5,  45903],
       [ 72600,   6083,      7, ...,  11843,      1,  94768],
       [ 48114,  42596,      1, ...,   6853,      2,  55840],
       ...,
       [138379,  25483,      2, ...,  12235,      4,  16998],
       [ 37782,  36071,      1, ...,   7536,      1,  68585],
       [116783,   8208,      6, ...,  10811,      0,  95345]], dtype=int64)

In [32]:
X_test

array([[ 35528,  21812,      3, ...,   3431,      1,  60586],
       [119218,  13625,      5, ...,   6369,      5,  40505],
       [ 82892,  14560,      3, ...,   6409,      2,  66280],
       ...,
       [ 52090,  48992,      5, ...,   3307,      1,  55896],
       [ 52893,  26377,      4, ...,   7217,      3,  84686],
       [145651,  46852,      2, ...,   8806,      4,  42808]], dtype=int64)

In [33]:
y_train

array([1, 1, 0, ..., 0, 1, 0])

In [34]:
y_test

array([2, 2, 0, ..., 1, 1, 2])

In [35]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(106879, 27)
(52643, 27)
(106879,)
(52643,)


In [36]:
dataset.dtypes

ID                          int64
Customer_ID                 int64
Month                       int64
Name                        int32
Age                         int64
SSN                         int64
Occupation                  int32
Annual_Income               int64
Monthly_Inhand_Salary       int64
Num_Bank_Accounts           int64
Num_Credit_Card             int64
Interest_Rate               int64
Num_of_Loan                 int64
Type_of_Loan                int32
Delay_from_due_date         int64
Num_of_Delayed_Payment      int64
Changed_Credit_Limit        int64
Num_Credit_Inquiries        int64
Credit_Mix                  int32
Outstanding_Debt            int64
Credit_Utilization_Ratio    int64
Credit_History_Age          int64
Payment_of_Min_Amount       int32
Total_EMI_per_month         int64
Amount_invested_monthly     int64
Payment_Behaviour           int32
Monthly_Balance             int64
Credit_Score                int32
dtype: object

In [37]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [38]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression()

In [39]:
y_pred = classifier.predict(X_test)

In [40]:
print(np.concatenate((y_test.reshape(len(y_test), 1), y_pred.reshape(len(y_pred), 1)), 1))

[[2 2]
 [2 0]
 [0 0]
 ...
 [1 1]
 [1 2]
 [2 2]]


In [41]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, y_pred)
print(cm)

[[14140   545  2806]
 [ 2664 12197  2752]
 [ 3596  3905 10038]]


In [42]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.6909750584123245


In [43]:
print(1 - accuracy_score(y_test, y_pred))

0.30902494158767546


In [44]:
from sklearn.tree import DecisionTreeClassifier
Dt=DecisionTreeClassifier()
Dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [45]:
y_pred=classifier.predict(X_test)

In [46]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, y_pred)
print(cm)

[[14140   545  2806]
 [ 2664 12197  2752]
 [ 3596  3905 10038]]


In [47]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.6909750584123245


In [48]:
y_pred = classifier.predict(X_test)

In [56]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=541,random_state=0)
classifier.fit(X_train,y_train)

RandomForestClassifier(n_estimators=541, random_state=0)

In [57]:
y_pred=classifier.predict(X_test)

In [58]:
n_errors=(y_pred!=y_test).sum()

In [59]:
n_errors

4437

In [60]:
y_test.shape

(52643,)

In [61]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm= confusion_matrix(y_test, y_pred)
print(cm)


[[17214     4   273]
 [   12 16955   646]
 [ 1366  2136 14037]]


In [62]:
print(accuracy_score(y_test, y_pred))

0.9157152897821172
